### ISSUE TITLE
Mono color icon required.

### ISSUE THREAD

**Issue by RuofengX** [rehhouari/gnome-shell-extension-syncthing-toggle#1]
Both light and dark, based on system setting.

**Comment by rehhouari** [comment]
Hey, can you please elaborate? I used a black svg which should change color accordingly, i just switched theme to light in appearence settings and through light style extension, it didnt have any effect on that area. am i missing something?

**Comment by RuofengX** [comment]
Thanks for your reply. 

The syncthing toggle on quick setting is really an awesome and useful extension for me. 

Here is a full explain:
This is a screen snapshot on the corner of my gnome desktop. You can see that every icon on the bar (except battery, which is charging) has a black color.  And when I switch to black shell theme, the icon color will turn to white. 
![images](https://github.com/user-attachments/assets/97b387c8-b079-45ce-9876-3f745c6ff4be)
![images-2](https://github.com/user-attachments/assets/9d8defc2-7975-4383-a20c-a8dcd9b4d07b)


I think the origin blue icon of syncthing is too outstanding for me. It is better to make the icon also mono-colored(black in light theme, white in dark) to achieve a harmony with system setting icons. Or, leave this icon as an option to user.

**Comment by rehhouari** [comment]
Thanks alot! I can reproduce this afte reinstalling it and removing the icon that I had already. Sorry for the inconvenience it's my first GNOME extension. I managed to resolve the issue and I'll push an update!

**Comment by rehhouari** [comment]
I pushed the update! v3 has the fix and it's currently waiting to be reviewed, it will probably be accepted in a few hours. Thanks again for the great report!

**Comment by rehhouari** [comment]
Update accepted! :partying_face:

**Comment by rauldipeas** [comment]
It's possible to use icon from theme? (Ex. Papirus)

**Comment by rehhouari** [comment]
> It's possible to use icon from theme? (Ex. Papirus)

You can now as of v7 set a custom icon name from the extension settings. it requires logging out to see the changes. To get the icon name look for the icon file name in `/usr/share/icons/YourIconTheme`
